export { default as About } from "./About"
export { default as Home } from "./Home"
export { default as Error404 } from "./Error404"
export { default as NewPost } from "./NewPost"
export { default as PostPage } from "./PostPage"